clusterGroup:
  name: prod
  namespaces:
    my-first-pattern:
    boutique: {}
  subscriptions: {}
  applications:
    boutique:
      name: boutique
      namespace: boutique
      chart: boutique
      chartVersion: 0.0.*
